################################################################################
[config]

mode = "r_w"

condition.type = "enumeration"
condition.description = "Set mode for how the counter operates."
condition.element.clock_cycles = "Increment counter each clock cycle."
condition.element.clock_cycles_with_enable = """
Increment counter each clock cycle when **clock_enable** is asserted.
"""
condition.element.enable_edges = """
Increment counter each time **clock_enable** changes state.
"""

increment.type = "integer"
increment.description = "How much to increment counter."
increment.max_value = 15


################################################################################
[command]

mode = "wpulse"

start.type = "bit"
start.description = "Write '1' to start operation."

stop.type = "bit"
stop.description = "Write '1' to stop operation."


################################################################################
[status]

mode = "r"

enabled.type = "bit"
enabled.description = "Reads as '1' if operation is enabled."

calibration_offset.type = "integer"
calibration_offset.min_value = -255
calibration_offset.max_value = 255
calibration_offset.description = """
Number of pulses that have been sent.
Will wrap around.
Value will be cleared to zero when **config** register is written.
"""

tdata.type = "bit_vector"
tdata.width = 4

state.type = "enumeration"
state.element.idle = "Informational message. Is not considered an error."
state.element.warning = "Warning message. Is not considered an error."
state.element.error = "Error message. Is considered an error."
state.element.failure = "Failure message. Is considered an error."
