# This will allocate a register constant with the name "base_address" of data type
# unsigned bit vector.
[base_address]

# The "type" property MUST be present and set to "constant".
type = "constant"

# The "value" property MUST be present for a bit vector constant.
# The value specified MUST be a string, and MUST start with either "0x" or "0b".
# Underscore (_) is allowed as a separator.
value = "0xA_0000_0000"

# The "data_type" MUST be provided to instruct the parser to interpret the "value" as an unsigned
# bit vector rather than a string.
data_type = "unsigned"

# The "description" property is OPTIONAL for a constant.
# Will default to "" if not specified.
# The value specified MUST be a string.
description = "Base address for this module on the register bus."


[data_mask]

type = "constant"
value = "0b1100_1111"
data_type = "unsigned"
