[conf]

mode = "r_w"
description = "Configuration register."

# This will allocate an integer field named "burst_length_bytes" in the "conf" register.
# The "type" property MUST be present and set to "integer".
burst_length_bytes.type = "integer"

# The "min_value" property is OPTIONAL for an integer field.
# Will default to 0 if not specified.
# The value specified MUST be an integer.
burst_length_bytes.min_value = 1

# The "max_value" property MUST be present for an integer field.
# The value specified MUST be an integer, and greater than or equal to the
# "min_value" parameter value.
burst_length_bytes.max_value = 256

# The "description" property is OPTIONAL for an integer field.
# Will default to "" if not specified.
# The value specified MUST be a string.
burst_length_bytes.description = "The number of bytes to request."

# The "default_value" property is OPTIONAL for a integer field.
# Will default to the "min_value" parameter value if not specified.
# The value specified MUST be an integer within the specified min/max range.
burst_length_bytes.default_value = 64


increment.type = "integer"
increment.min_value = -4
increment.max_value = 3
increment.description = "Offset that will be added to data."
increment.default_value = 0


retry_count.type = "integer"
retry_count.max_value = 5
retry_count.description = "Number of retry attempts before giving up."
